<?php

/**
 * Do not edit this file directly, instead copy it as cargo.php and place it
 * into your config directory.
 */

return [
    /**
     * The Algolia application ID and secret.
     */
    'algolia' => [
        'id' => '',
        'secret' => '',
    ],

    /**
     * The size of the batch used when updating Algolia indices.
     * If you are having issues with timeouts, try lowering this number.
     */
    'batchSize' => 100,

    /**
     * Your Algolia indices and the Craft entries that should be synced to them.
     */
    'indices' => [],
];
